from crewai import Task
from agents import (
    repository_recommender,
    repository_explainer,
    skill_analyzer,
    issue_recommender,
    roadmap_creator,
    checklist_creator
)

skill_task = Task(
    description="""
Use GitHub User Profile tool.

Analyze the profile.

""",
    expected_output="""
    Return ONLY JSON:

    {
    "github_data_used": true,
    "languages": [],
    "experience_level": "",
    "interests": [],
    "notes":""
    }
    """,
    agent=skill_analyzer,
)


repository_task = Task(
    description = """
You are an expert Open Source Mentor and GitHub Repository Recommendation Engine.

Your job is to recommend the most suitable GitHub repositories for a developer based on their analyzed developer profile and, if applicable, evaluate a repository explicitly chosen by the user.

The developer profile below has already been generated by the Skill Analyzer.

=========================================================
Developer Profile
=========================================================

{developer_profile}

=========================================================
Developer Selected Repository
=========================================================

{user_repository}

=========================================================
Primary Objectives
=========================================================

1. Always generate personalized GitHub repository recommendations.

2. If the user has explicitly provided a repository, evaluate whether it matches the developer's current skill level.

3. Recommend repositories using ONLY real repositories returned by the GitHub Repository Search Tool.

4. Never invent repository names, owners, URLs, technologies, or statistics.

5. Base every recommendation on the developer profile and verified GitHub repository information.

=========================================================
STEP 1 : Repository Recommendation (Always Execute)
=========================================================

This step MUST ALWAYS execute, regardless of whether the user supplied a repository.

Use the GitHub Repository Search Tool to search for repositories that best match the developer profile.

Construct search queries using available developer information such as:

• Programming languages
• Frameworks
• Technologies
• Interests
• Experience level
• Skill level

Examples:

language:python good-first-issues
language:typescript react
language:java spring
machine-learning beginner
fastapi stars:100..10000

Do NOT invent repositories.

Recommend ONLY repositories returned by the GitHub Repository Search Tool.

Generate EXACTLY 10 repositories whenever enough suitable repositories are available.

If fewer than 10 suitable repositories are found using the GitHub Repository Search Tool, return all verified repositories that match the developer profile.

=========================================================
STEP 2 : User Repository Selection (No Suitability Check)
=========================================================

If the user provided a repository ({user_repository} is not "not provided"):

Validate ONLY that the repository actually exists using the GitHub tools
(i.e. it can be found and its metadata fetched). Do NOT evaluate whether
it "matches" the developer's skill level, and do NOT reject it for being
too easy or too hard.

If the repository exists:

status = "PROVIDED"

selected_repository = the validated user repository (exactly as given).

Continue returning the complete ranked recommendation list. The selected
repository may also appear in that list if it naturally qualifies based on
its overall score — this does not affect the fact that it is already
selected_repository.

If the repository genuinely cannot be found or does not exist:

status = "INVALID"

selected_repository = {}

Explain plainly that the repository could not be found or verified.

Continue returning the ranked recommendation list based on the developer
profile.

Do NOT fabricate repository information.

=========================================================
STEP 3 : Automatic Repository Selection
=========================================================

If {user_repository} == "not provided" (or empty / null):

status = "AUTO"

Generate personalized recommendations.

The repository ranked #1 automatically becomes:

selected_repository

This selected repository will be used by downstream agents for:

• Repository Explanation
• Issue Recommendation
• Contribution Roadmap
• Contribution Checklist

Never choose any repository other than:

• the validated user repository (PROVIDED)

OR

• Rank #1 recommendation (AUTO)

=========================================================
STEP 4 : Repository Scoring Engine
=========================================================

For EVERY recommended repository calculate the following scores.

---------------------------------------------------------
1. Language Match Score (0-100)
---------------------------------------------------------

Evaluate how closely the repository's primary language(s)
match the developer profile.

Examples:

100 = Primary language perfectly matches
80 = Strong match
60 = Partial match
30 = Weak match
0 = No meaningful match

---------------------------------------------------------
2. Skill Match Score (0-100)
---------------------------------------------------------

Evaluate how closely the repository requirements match the
developer's current skills.

Consider:

• Frameworks
• Libraries
• Backend knowledge
• Frontend knowledge
• Databases
• Cloud
• DevOps
• Testing
• APIs

A repository requiring many unknown technologies should
receive a lower score.

---------------------------------------------------------
3. Repository Activity Score (0-100)
---------------------------------------------------------

Estimate repository activity using available GitHub metadata.

Consider:

• Recent commits
• Active maintainers
• Pull requests
• Community engagement
• Repository health

Higher activity should receive a higher score.

---------------------------------------------------------
4. Issue Friendliness Score (0-100)
---------------------------------------------------------

Consider:

• Good First Issues
• Beginner labels
• Help Wanted labels
• Issue descriptions
• Ease of onboarding

Repositories suitable for newcomers should receive higher
scores.

---------------------------------------------------------
5. Documentation Quality Score (0-100)
---------------------------------------------------------

Evaluate:

• README completeness
• Installation guide
• Contribution guide
• Project explanation
• Examples
• API documentation

Better documentation should receive higher scores.

---------------------------------------------------------
6. Difficulty
---------------------------------------------------------

Difficulty must be EXACTLY one of:

Easy

Medium

Hard

Estimate difficulty using:

• Code complexity
• Technologies used
• Repository size
• Contribution process
• Required experience

=========================================================
STEP 5 : Overall Recommendation Score
=========================================================

Calculate:

Overall Score =

0.35 × Language Match

+

0.20 × Repository Activity

+

0.15 × Issue Friendliness

+

0.15 × Documentation Quality

+

0.15 × Skill Match

Round the result to the nearest integer.

Overall Score must always be an integer between 0 and 100.

=========================================================
STEP 6 : Repository Ranking
=========================================================

Sort repositories using the following priority:

1.
Highest Overall Score

If tied:

2.
Easier Difficulty

Easy

↓

Medium

↓

Hard

If still tied:

3.
Higher Repository Activity Score

If still tied:

4.
Better Documentation Quality

If still tied:

5.
Higher Skill Match Score

The first repository must always represent the strongest
overall recommendation.

=========================================================
STEP 7 : Recommendation Explanation
=========================================================

For EVERY repository explain WHY it was recommended.

Reasons must be specific.

Good examples:

✓ Strong language match

✓ React experience aligns with repository

✓ Uses technologies already known

✓ Beginner-friendly contribution process

✓ Active maintainers

✓ Excellent documentation

✓ Good First Issues available

✓ Suitable project size

Avoid vague statements like:

Good repository

Nice project

Interesting project

Looks useful

Every reason must be supported by repository evidence.

=========================================================
JSON Response Format
=========================================================

Return ONLY ONE valid JSON object.

{
    "status": "PROVIDED | AUTO | INVALID",

    "message": "Short explanation for the user.",

    "selected_repository": {},

    "recommended_repositories": [

        {
            "rank": 1,

            "repository": "",

            "owner": "",

            "url": "",

            "overall_score": 94,

            "difficulty": "Easy",

            "language_match": 98,

            "skill_match": 95,

            "repository_activity": 90,

            "issue_friendliness": 92,

            "documentation_quality": 94,

            "matched_skills": [

                "Python",

                "FastAPI",

                "Git"

            ],

            "reason": [

                "Strong language match",

                "Excellent documentation",

                "Good First Issues",

                "Active maintainers"

            ]
        }

    ]
}

=========================================================
Rules
=========================================================

Return ONLY valid JSON.

Do NOT return:

• Markdown

• Triple backticks

• Explanations

• Commentary

• Extra text

• Notes outside the JSON object

---------------------------------------------------------
Repository Requirements
---------------------------------------------------------

Recommend ONLY repositories returned by the GitHub Repository Search Tool.

Never invent:

• Repository names

• Owners

• URLs

• Languages

• Topics

• Technologies

• Statistics

• Stars

• Forks

• Activity

If repository information cannot be verified, do not fabricate it.

---------------------------------------------------------
Technology Detection
---------------------------------------------------------

Only include technologies that can reasonably be inferred from:

• Repository language

• Topics

• README

• Repository description

• File structure

Do NOT assume technologies simply because they are commonly used together.

For example:

If React is detected,

do NOT automatically assume:

• Redux

• Tailwind

• Vite

• Firebase

unless repository evidence supports them.

---------------------------------------------------------
Recommendation Rules
---------------------------------------------------------

Return AT MOST 10 repositories.

If fewer than 10 suitable repositories are available,

return as many verified repositories as possible.

Do not duplicate repositories.

Every recommended repository must be unique.

Always return repositories in descending order of overall_score.

If two repositories have nearly equal overall_score (difference less than 3 points), prefer the repository with the lower difficulty.

Repositories must always be sorted according to the Ranking Rules.

=========================================================
Repository Selection Rules
=========================================================

Repository recommendations must ALWAYS be generated, no matter what.

There is NO suitability check on the user-provided repository — it is
never evaluated against the developer profile and can never be rejected
for being "too easy" or "too hard." The only question for a user-provided
repository is whether it exists.

After generating recommendations, decide selected_repository using
exactly one of these two cases:

---------------------------------------------------------
CASE 1: User provided a repository
---------------------------------------------------------

If user_repository is provided (not "not provided", not empty, not null):

1. Validate the repository exists using GitHub tools.

2. If it exists:

status = "PROVIDED"

selected_repository = the validated user repository, exactly as given.

The user-selected repository has priority for downstream analysis. It
does not need to be rank #1, and it is used regardless of how well it
fits the developer profile.

Continue returning the complete recommendation list.

3. If it cannot be found / does not exist:

status = "INVALID"

selected_repository = {}

Explain plainly that the repository could not be found or verified.

Continue returning the recommendation list based on the developer profile.

---------------------------------------------------------
CASE 2: User did not provide a repository
---------------------------------------------------------

If:

user_repository == "not provided"

or empty

or null

Then:

status = "AUTO"

selected_repository must be:

Rank #1 repository from recommended_repositories.

---------------------------------------------------------
Downstream Agent Rules
---------------------------------------------------------

The selected_repository will be used by all downstream agents.

Repository Explainer

Issue Recommendation

Contribution Roadmap

Contribution Checklist

Those agents must analyze ONLY the selected_repository.

They must NEVER switch to another repository.

---------------------------------------------------------
Scoring Rules
---------------------------------------------------------

overall_score

language_match

skill_match

repository_activity

issue_friendliness

documentation_quality

must all be integers between 0 and 100.

difficulty must always be exactly one of:

Easy

Medium

Hard

rank must begin from 1.

---------------------------------------------------------
Reason Rules
---------------------------------------------------------

Every repository must include between 3 and 5 concise reasons.

Each reason must be directly supported by verified GitHub repository evidence.

Reasons must be concise.

Reasons must be supported by repository evidence.

Avoid generic phrases like:

"Looks interesting"

"Popular project"

"Good repository"

---------------------------------------------------------
Strict JSON Rules
---------------------------------------------------------

Return exactly ONE JSON object.

Do not wrap JSON inside markdown.

Do not return any explanation before the JSON.

Do not return any explanation after the JSON.

Return valid JSON that can be parsed directly using json.loads().

=========================================================
Expected Output
=========================================================

Return exactly one valid JSON object containing:

status

message

selected_repository

recommended_repositories

recommended_repositories must contain up to 10 ranked repositories.

Each repository must contain:

rank

repository

owner

url

overall_score

difficulty

language_match

skill_match

repository_activity

issue_friendliness

documentation_quality

matched_skills

reason

The response must be immediately parseable using Python's json.loads() without any preprocessing.

This task must always produce a valid recommendation result based only on verified GitHub data and the provided developer profile.
""",
    expected_output="""
Return exactly one valid JSON object.

The JSON must contain:

- status
- message
- selected_repository
- recommended_repositories

Each recommended repository must include:
rank, repository, owner, url, overall_score,
difficulty, language_match, skill_match,
repository_activity, issue_friendliness,
documentation_quality, matched_skills and reason.

Return ONLY raw JSON.
No markdown.
No explanations.
The output must be directly parseable using Python's json.loads().
""",
    agent=repository_recommender,
)


explanation_task = Task(
    description="""
Explain the selected_repository returned by repository_task, in
beginner-friendly language.

Rules for choosing which repository to explain:
- If the user provided a repository and repository_task validated it
  (status == "PROVIDED"), analyze that selected_repository.
- If the user did not provide a repository (status == "AUTO"), analyze the
  rank #1 recommended repository, which repository_task set as
  selected_repository.
- Never switch to another repository from the recommendation list.
- If selected_repository is empty (status == "INVALID"),
  state plainly that no repository could be selected for explanation and
  do not fabricate one.

Use the GitHub Repository Info, README Fetcher, and File Tree tools to get
real data about the repository before writing the explanation. Base your
explanation only on what the tools return.

Generate the following sections:

# Repository Overview
What does this project do? What problem does it solve? Who is the target audience?

# Project Architecture
Explain the overall structure of the project.

# Core Components
Explain ONLY the important folders/files that actually exist in this repository (from the File Tree tool) and what each one does.

# Tech Stack
Mention only technologies actually used: Programming Language, Framework, Libraries, Package Manager, Build Tool, Testing Framework.

# Project Workflow
Explain how the project works internally from start to finish.

# Key Features
List the major features of this project.

# Learning Path
Suggest the order in which a beginner should explore this repository to understand it.

Rules:
- Do NOT talk about contribution or GitHub issues in this task.
- Do NOT explain missing files or write "not present".
- Keep explanations concise and repository-specific.
- Return clean Markdown only.
""",
    expected_output="A Markdown document with sections: Repository Overview, Project Architecture, Core Components, Tech Stack, Project Workflow, Key Features, Learning Path — grounded in real fetched data about the selected_repository.",
    agent=repository_explainer,
    context=[repository_task]
)

issue_task = Task(
    description="""
Recommend beginner-friendly GitHub issues only from the selected_repository
returned by repository_task.

The repository to use must come exclusively from repository_task's output
(selected_repository). Never switch repositories, and never pick a
different repository from the recommendation list.

Use the GitHub Open Issues tool to fetch the real open issues for this
repository. Only recommend issues that were actually returned by the tool —
never invent issue numbers or titles. If the tool returns no issues, say so
plainly instead of making some up.

If selected_repository is empty (status == "INVALID"), state
plainly that no repository was selected and no issues can be recommended.

How many issues to include:
- If the tool returns FEWER than 10 open issues, include ALL of them.
- If the tool returns 10 or MORE open issues, select and include exactly
  the TOP 10.
- Always sort the included issues from EASIEST to HARDEST difficulty
  (Easy issues first, then Medium, then Hard). Order matters — do not list
  them in the order the tool returned them.

For each recommended issue, provide:
- Issue Title
- Difficulty (Easy/Medium/Hard)
- Why it is suitable
- Skills Required
- Estimated Time
- Learning Outcome

Return the result in clean Markdown.
""",
    expected_output="A Markdown list of beginner-friendly issues from the selected_repository (all of them if the repo has fewer than 10 open issues, otherwise the top 10), sorted from Easy to Hard, each with Issue Title, Difficulty, Why it is suitable, Skills Required, Estimated Time, Learning Outcome — all backed by real tool data (real issue numbers/titles).",
    agent=issue_recommender,
    context=[repository_task]
)

roadmap_task = Task(
    description="""
Create a step-by-step contribution roadmap only for the selected_repository
returned by repository_task, tailored to a developer with experience
level: {experience}.

Never select another repository from the recommendation list — use only
the repository repository_task set as selected_repository.

If selected_repository is empty (status == "INVALID"), state
plainly that no repository was selected and a roadmap cannot be generated.

Use the README Fetcher, Open Issues, and CONTRIBUTING.md Fetcher tools to
ground the roadmap in the repository's actual setup instructions and
contribution rules, not generic assumptions.

Generate the following sections:

# Repository Setup
How to set up this specific repository locally: installation commands, dependencies, build steps, test commands (only if available).

# Where Should a Beginner Start?
Recommend the first files, folders, or documentation to read before contributing, and explain why.

# First Contribution Recommendation
Recommend ONE beginner-friendly contribution based on this repository: File/Folder to modify, Estimated difficulty (Easy/Medium/Hard), Estimated time, Why it is a good first contribution.

# Contribution Opportunities
Suggest contributions specific to this repository under: ## Beginner, ## Intermediate, ## Advanced.

# Open Issues Analysis
From the real fetched issues: recommend the best beginner-friendly ones, explain why each is suitable, mention required skills.

# Skills Required
List the languages, frameworks, and tools required to contribute to THIS repository.

# Contribution Workflow
Fork -> Clone -> Setup -> Create Branch -> Code -> Test -> Commit -> Push -> Pull Request. Mention repository-specific steps if available in the README.

# Common Mistakes to Avoid
List common mistakes beginners should avoid when contributing to this repository.

# 30-Day Contribution Plan
A realistic week-by-week plan to become capable of contributing successfully to this repository.

Rules:
- Make every recommendation repository-specific, grounded in the real README/CONTRIBUTING.md/issues data.
- Do NOT explain the repository architecture (that belongs to the explanation task).
- Do NOT invent information not supported by the repository.
- Return clean Markdown only.
""",
    expected_output="A Markdown roadmap with sections: Repository Setup, Where Should a Beginner Start, First Contribution Recommendation, Contribution Opportunities, Open Issues Analysis, Skills Required, Contribution Workflow, Common Mistakes to Avoid, 30-Day Contribution Plan — for the selected_repository only.",
    agent=roadmap_creator,
    context=[repository_task]
)

checklist_task = Task(
    description="""
Generate a pull request PREPARATION checklist for a contributor about to
submit work only to the selected_repository returned by repository_task.
This is a pre-submission checklist (the contributor has not opened a PR
yet), not a review of an existing PR.

Never switch repositories — use only the repository repository_task set as
selected_repository.

If selected_repository is empty (status == "INVALID"), state
plainly that no repository was selected and a checklist cannot be
generated.

Use the CONTRIBUTING.md Fetcher tool to base the checklist on this
repository's actual contribution rules where available, falling back to
general open-source best practices only for anything CONTRIBUTING.md
doesn't cover.

Organize the checklist under these sections:

### Pre-Submission Checklist
Repository familiarization, issue selection, development environment setup, code changes, testing and validation.

### Pull Request Preparation
Commit message quality, PR creation (title, description, linked issue, summary of changes).

### Final Checklist
Repository guidelines followed, code quality, testing and validation, PR readiness.

Rules:
- Ground every item in the real CONTRIBUTING.md content where it exists; note explicitly where you're falling back to general best practice because CONTRIBUTING.md didn't cover something.
- Return clean Markdown only.
""",
    expected_output="A Markdown pre-submission checklist with sections: Pre-Submission Checklist, Pull Request Preparation, Final Checklist — grounded in the real CONTRIBUTING.md rules where available, for the selected_repository only.",
    agent=checklist_creator,
    context=[roadmap_task]
)